services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: patchwork
      POSTGRES_PASSWORD: patchwork
      POSTGRES_DB: patchwork
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  mock-oidc:
    image: ghcr.io/cdelmonte-zg/nanoidp:latest
    environment:
      - NANOIDP_CONFIG_DIR=/app/config
    ports:
      - "8888:8000"
    volumes:
      - ./.nanoidp:/app/data
      - ./resources/local/oidc_config:/app/config:ro

volumes:
  db_data:
