// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBookmarksByCollectionId = `-- name: GetBookmarksByCollectionId :many
SELECT
    bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id,
    users.id, users.email, users.identity_id, users.created_at, users.updated_at, users.last_login_at,
    bookmark_tags.tag as tag,
    collection_bookmarks.added_at as added_at
FROM bookmarks
JOIN collection_bookmarks ON bookmarks.id = collection_bookmarks.bookmark_id
JOIN bookmark_tags ON bookmarks.id = bookmark_tags.bookmark_id
JOIN users ON bookmarks.author_id = users.id
WHERE collection_bookmarks.collection_id = $1
`

type GetBookmarksByCollectionIdRow struct {
	Bookmark Bookmark
	User     User
	Tag      string
	AddedAt  pgtype.Timestamp
}

func (q *Queries) GetBookmarksByCollectionId(ctx context.Context, collectionID uuid.UUID) ([]GetBookmarksByCollectionIdRow, error) {
	rows, err := q.db.Query(ctx, getBookmarksByCollectionId, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksByCollectionIdRow
	for rows.Next() {
		var i GetBookmarksByCollectionIdRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.User.ID,
			&i.User.Email,
			&i.User.IdentityID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.Tag,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBookmarksByUserId = `-- name: GetRecentBookmarksByUserId :many

SELECT
    bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id,
    users.id, users.email, users.identity_id, users.created_at, users.updated_at, users.last_login_at,
    bookmark_tags.tag as tag
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
JOIN bookmark_tags ON bookmarks.id = bookmark_tags.bookmark_id
WHERE bookmarks.author_id = $1
ORDER BY bookmarks.created_at DESC
LIMIT 10
`

type GetRecentBookmarksByUserIdRow struct {
	Bookmark Bookmark
	User     User
	Tag      string
}

func (q *Queries) GetRecentBookmarksByUserId(ctx context.Context, authorID pgtype.UUID) ([]GetRecentBookmarksByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getRecentBookmarksByUserId, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentBookmarksByUserIdRow
	for rows.Next() {
		var i GetRecentBookmarksByUserIdRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.User.ID,
			&i.User.Email,
			&i.User.IdentityID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
