// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookmarks.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (id, url, title, author_id)
VALUES ($1, $2, $3, $4::uuid)
RETURNING id, url, title, created_at, updated_at, archived_at, author_id, notes
`

type CreateBookmarkParams struct {
	ID       uuid.UUID
	Url      string
	Title    string
	AuthorID uuid.UUID
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRow(ctx, createBookmark,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.AuthorID,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.AuthorID,
		&i.Notes,
	)
	return i, err
}

type CreateBookmarkTagsParams struct {
	BookmarkID uuid.UUID
	Tag        string
	AuthorID   uuid.UUID
}

const createCollectionBookmark = `-- name: CreateCollectionBookmark :one
INSERT INTO collection_bookmarks (collection_id, bookmark_id)
VALUES ($1, $2)
RETURNING collection_id, bookmark_id, added_at
`

type CreateCollectionBookmarkParams struct {
	CollectionID uuid.UUID
	BookmarkID   uuid.UUID
}

func (q *Queries) CreateCollectionBookmark(ctx context.Context, arg CreateCollectionBookmarkParams) (CollectionBookmark, error) {
	row := q.db.QueryRow(ctx, createCollectionBookmark, arg.CollectionID, arg.BookmarkID)
	var i CollectionBookmark
	err := row.Scan(&i.CollectionID, &i.BookmarkID, &i.AddedAt)
	return i, err
}

const getAllBookmarksByUserId = `-- name: GetAllBookmarksByUserId :many
SELECT bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes, users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
WHERE bookmarks.author_id = $1::uuid
AND ($2::text = '' OR bookmarks.title ILIKE '%' || $2::text || '%' OR bookmarks.url ILIKE '%' || $2::text || '%')
ORDER BY bookmarks.created_at DESC
LIMIT 20
`

type GetAllBookmarksByUserIdParams struct {
	AuthorID uuid.UUID
	Search   string
}

type GetAllBookmarksByUserIdRow struct {
	Bookmark Bookmark
	User     User
}

func (q *Queries) GetAllBookmarksByUserId(ctx context.Context, arg GetAllBookmarksByUserIdParams) ([]GetAllBookmarksByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAllBookmarksByUserId, arg.AuthorID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBookmarksByUserIdRow
	for rows.Next() {
		var i GetAllBookmarksByUserIdRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksByCollection = `-- name: GetBookmarksByCollection :many
SELECT bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes, users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
JOIN collection_bookmarks ON bookmarks.id = collection_bookmarks.bookmark_id
WHERE collection_bookmarks.collection_id = $1
AND ($2::text = '' OR bookmarks.title ILIKE '%' || $2::text || '%' OR bookmarks.url ILIKE '%' || $2::text || '%')
ORDER BY bookmarks.created_at DESC
LIMIT 20
`

type GetBookmarksByCollectionParams struct {
	CollectionID uuid.UUID
	Search       string
}

type GetBookmarksByCollectionRow struct {
	Bookmark Bookmark
	User     User
}

func (q *Queries) GetBookmarksByCollection(ctx context.Context, arg GetBookmarksByCollectionParams) ([]GetBookmarksByCollectionRow, error) {
	rows, err := q.db.Query(ctx, getBookmarksByCollection, arg.CollectionID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksByCollectionRow
	for rows.Next() {
		var i GetBookmarksByCollectionRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksByCollectionAndTags = `-- name: GetBookmarksByCollectionAndTags :many
SELECT bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes, users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
JOIN collection_bookmarks ON bookmarks.id = collection_bookmarks.bookmark_id
JOIN bookmark_tags ON bookmarks.id = bookmark_tags.bookmark_id
WHERE collection_bookmarks.collection_id = $1
AND bookmark_tags.tag = ANY($2::text[])
AND ($3::text = '' OR bookmarks.title ILIKE '%' || $3::text || '%' OR bookmarks.url ILIKE '%' || $3::text || '%')
ORDER BY bookmarks.created_at DESC
LIMIT 20
`

type GetBookmarksByCollectionAndTagsParams struct {
	CollectionID uuid.UUID
	Tags         []string
	Search       string
}

type GetBookmarksByCollectionAndTagsRow struct {
	Bookmark Bookmark
	User     User
}

func (q *Queries) GetBookmarksByCollectionAndTags(ctx context.Context, arg GetBookmarksByCollectionAndTagsParams) ([]GetBookmarksByCollectionAndTagsRow, error) {
	rows, err := q.db.Query(ctx, getBookmarksByCollectionAndTags, arg.CollectionID, arg.Tags, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksByCollectionAndTagsRow
	for rows.Next() {
		var i GetBookmarksByCollectionAndTagsRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksByCollectionId = `-- name: GetBookmarksByCollectionId :many
SELECT
    bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes,
    users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash,
    bookmark_tags.tag as tag,
    collection_bookmarks.added_at as added_at
FROM bookmarks
JOIN collection_bookmarks ON bookmarks.id = collection_bookmarks.bookmark_id
LEFT JOIN bookmark_tags ON bookmarks.id = bookmark_tags.bookmark_id
JOIN users ON bookmarks.author_id = users.id
WHERE collection_bookmarks.collection_id = $1
ORDER BY bookmarks.created_at DESC
`

type GetBookmarksByCollectionIdRow struct {
	Bookmark Bookmark
	User     User
	Tag      pgtype.Text
	AddedAt  pgtype.Timestamp
}

func (q *Queries) GetBookmarksByCollectionId(ctx context.Context, collectionID uuid.UUID) ([]GetBookmarksByCollectionIdRow, error) {
	rows, err := q.db.Query(ctx, getBookmarksByCollectionId, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksByCollectionIdRow
	for rows.Next() {
		var i GetBookmarksByCollectionIdRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
			&i.Tag,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksByTags = `-- name: GetBookmarksByTags :many
SELECT DISTINCT ON (bookmarks.id)
    bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes, users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
JOIN bookmark_tags ON bookmarks.id = bookmark_tags.bookmark_id
WHERE bookmark_tags.tag = ANY($1::text[])
AND bookmarks.author_id = $2::uuid
AND ($3::text = '' OR bookmarks.title ILIKE '%' || $3::text || '%' OR bookmarks.url ILIKE '%' || $3::text || '%')
ORDER BY bookmarks.id, bookmarks.created_at DESC
LIMIT 20
`

type GetBookmarksByTagsParams struct {
	Tags     []string
	AuthorID uuid.UUID
	Search   string
}

type GetBookmarksByTagsRow struct {
	Bookmark Bookmark
	User     User
}

func (q *Queries) GetBookmarksByTags(ctx context.Context, arg GetBookmarksByTagsParams) ([]GetBookmarksByTagsRow, error) {
	rows, err := q.db.Query(ctx, getBookmarksByTags, arg.Tags, arg.AuthorID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksByTagsRow
	for rows.Next() {
		var i GetBookmarksByTagsRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBookmarksByUserId = `-- name: GetRecentBookmarksByUserId :many
SELECT bookmarks.id, bookmarks.url, bookmarks.title, bookmarks.created_at, bookmarks.updated_at, bookmarks.archived_at, bookmarks.author_id, bookmarks.notes, users.id, users.email, users.created_at, users.updated_at, users.last_login_at, users.password_hash
FROM bookmarks
JOIN users ON bookmarks.author_id = users.id
WHERE bookmarks.author_id = $1::uuid
AND ($2::text = '' OR bookmarks.title ILIKE '%' || $2::text || '%' OR bookmarks.url ILIKE '%' || $2::text || '%')
ORDER BY bookmarks.created_at DESC
LIMIT 10
`

type GetRecentBookmarksByUserIdParams struct {
	AuthorID uuid.UUID
	Search   string
}

type GetRecentBookmarksByUserIdRow struct {
	Bookmark Bookmark
	User     User
}

func (q *Queries) GetRecentBookmarksByUserId(ctx context.Context, arg GetRecentBookmarksByUserIdParams) ([]GetRecentBookmarksByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getRecentBookmarksByUserId, arg.AuthorID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentBookmarksByUserIdRow
	for rows.Next() {
		var i GetRecentBookmarksByUserIdRow
		if err := rows.Scan(
			&i.Bookmark.ID,
			&i.Bookmark.Url,
			&i.Bookmark.Title,
			&i.Bookmark.CreatedAt,
			&i.Bookmark.UpdatedAt,
			&i.Bookmark.ArchivedAt,
			&i.Bookmark.AuthorID,
			&i.Bookmark.Notes,
			&i.User.ID,
			&i.User.Email,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByBookmarkIds = `-- name: GetTagsByBookmarkIds :many
SELECT bookmark_id, tag
FROM bookmark_tags
WHERE bookmark_id = ANY($1::uuid[])
`

type GetTagsByBookmarkIdsRow struct {
	BookmarkID uuid.UUID
	Tag        string
}

func (q *Queries) GetTagsByBookmarkIds(ctx context.Context, bookmarkIds []uuid.UUID) ([]GetTagsByBookmarkIdsRow, error) {
	rows, err := q.db.Query(ctx, getTagsByBookmarkIds, bookmarkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByBookmarkIdsRow
	for rows.Next() {
		var i GetTagsByBookmarkIdsRow
		if err := rows.Scan(&i.BookmarkID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByUserId = `-- name: GetTagsByUserId :many
SELECT
    tag,
    COUNT(*) as bookmark_count
FROM bookmark_tags
WHERE author_id = $1
GROUP BY tag
`

type GetTagsByUserIdRow struct {
	Tag           string
	BookmarkCount int64
}

func (q *Queries) GetTagsByUserId(ctx context.Context, authorID uuid.UUID) ([]GetTagsByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getTagsByUserId, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByUserIdRow
	for rows.Next() {
		var i GetTagsByUserIdRow
		if err := rows.Scan(&i.Tag, &i.BookmarkCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
