// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCollectionMember = `-- name: AddCollectionMember :exec
INSERT INTO collection_members (collection_id, user_id, role) VALUES ($1, $2, $3)
`

type AddCollectionMemberParams struct {
	CollectionID uuid.UUID
	UserID       uuid.UUID
	Role         string
}

func (q *Queries) AddCollectionMember(ctx context.Context, arg AddCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, addCollectionMember, arg.CollectionID, arg.UserID, arg.Role)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, name, description) VALUES ($1, $2, $3) RETURNING id, name, description, created_at, updated_at
`

type CreateCollectionParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.ID, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionById = `-- name: GetCollectionById :one
SELECT collections.id, collections.name, collections.description, collections.created_at, collections.updated_at, collection_members.collection_id, collection_members.user_id, collection_members.role, collection_members.added_at
FROM collections
JOIN collection_members ON collections.id = collection_members.collection_id
WHERE collections.id = $1
`

type GetCollectionByIdRow struct {
	Collection       Collection
	CollectionMember CollectionMember
}

func (q *Queries) GetCollectionById(ctx context.Context, id uuid.UUID) (GetCollectionByIdRow, error) {
	row := q.db.QueryRow(ctx, getCollectionById, id)
	var i GetCollectionByIdRow
	err := row.Scan(
		&i.Collection.ID,
		&i.Collection.Name,
		&i.Collection.Description,
		&i.Collection.CreatedAt,
		&i.Collection.UpdatedAt,
		&i.CollectionMember.CollectionID,
		&i.CollectionMember.UserID,
		&i.CollectionMember.Role,
		&i.CollectionMember.AddedAt,
	)
	return i, err
}

const getCollectionsByUser = `-- name: GetCollectionsByUser :many
SELECT collections.id, collections.name, collections.description, collections.created_at, collections.updated_at, collection_members.collection_id, collection_members.user_id, collection_members.role, collection_members.added_at
FROM collections
JOIN collection_members ON collections.id = collection_members.collection_id
WHERE collection_members.user_id = $1
`

type GetCollectionsByUserRow struct {
	Collection       Collection
	CollectionMember CollectionMember
}

func (q *Queries) GetCollectionsByUser(ctx context.Context, userID uuid.UUID) ([]GetCollectionsByUserRow, error) {
	rows, err := q.db.Query(ctx, getCollectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionsByUserRow
	for rows.Next() {
		var i GetCollectionsByUserRow
		if err := rows.Scan(
			&i.Collection.ID,
			&i.Collection.Name,
			&i.Collection.Description,
			&i.Collection.CreatedAt,
			&i.Collection.UpdatedAt,
			&i.CollectionMember.CollectionID,
			&i.CollectionMember.UserID,
			&i.CollectionMember.Role,
			&i.CollectionMember.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionMember = `-- name: RemoveCollectionMember :exec
DELETE FROM collection_members WHERE collection_id = $1 AND user_id = $2
`

type RemoveCollectionMemberParams struct {
	CollectionID uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) RemoveCollectionMember(ctx context.Context, arg RemoveCollectionMemberParams) error {
	_, err := q.db.Exec(ctx, removeCollectionMember, arg.CollectionID, arg.UserID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections SET name = $2, description = $3 WHERE id = $1 RETURNING id, name, description, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection, arg.ID, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
