// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateBookmarkTags implements pgx.CopyFromSource.
type iteratorForCreateBookmarkTags struct {
	rows                 []CreateBookmarkTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBookmarkTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBookmarkTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookmarkID,
		r.rows[0].Tag,
		r.rows[0].AuthorID,
	}, nil
}

func (r iteratorForCreateBookmarkTags) Err() error {
	return nil
}

func (q *Queries) CreateBookmarkTags(ctx context.Context, arg []CreateBookmarkTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"bookmark_tags"}, []string{"bookmark_id", "tag", "author_id"}, &iteratorForCreateBookmarkTags{rows: arg})
}
