// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID          uuid.UUID
	Email       string
	IdentityID  string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	LastLoginAt pgtype.Timestamp
}
