// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (id, email, password_hash)
values ($1, $2, $3)
returning id, email, created_at, updated_at, last_login_at, password_hash
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, created_at, updated_at, last_login_at, password_hash from users
where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, email, created_at, updated_at, last_login_at, password_hash from users
where id = $1 limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
	)
	return i, err
}

const setUserLastLoginAt = `-- name: SetUserLastLoginAt :exec
update users
set last_login_at = now()
where id = $1
`

func (q *Queries) SetUserLastLoginAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserLastLoginAt, id)
	return err
}
